apiVersion: v1
data:
    password: ENC[AES256_GCM,data:fC53PcpeK8L/XC78LPsVL5s2HMD4P2IPjNrP1oClFnFCmtmyfdzl/8tG03sS2QiKGG9E8AsZm1rz3ytaP53tQiITTfGEiTJ15Q0/o696LKZY1znNPLR8NG7mZVI1YepBH/IvEtAOeiiXlHB7ME5yByXlULLYZX3nRS2oIhMHnrWrZOnWqWRkJrafEapCxd9PByFbjcvuqVj59QVlp4MasTqap2tAM2ghQTNGF1wkyOF/i3octRiioB+tuyYlI4eY,iv:uVG2PTOhGt26rXHNtNY9Uaw6ycCX0reqWFAXecE2900=,tag:Cf0hF2cDlt97OE7dHxFelw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-cloud-fleet
    namespace: monitoring
sops:
    age:
        - recipient: age1v64geenru82d3f2fl534lsu8dwdqlvnx665gsx4yxq4e3cdkyyzq38kgd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWXRxa2FDRTFHQWJvZVpq
            cWtKRE83d1cvc2thOURKWlZPZGN4UUxtclJBCklYcVFDamE1c0g3R1h5ZTcwMjNJ
            YjRKRXhmMURUWW1xdW1rZ3BuVmFoWFUKLS0tIE4xNzgxcjFFS3VuQ3NZU3EyTUlN
            VDhCV242QjNVRU5UcDVDS1RPdFhsWlkKy7daLQbfvNBQ0VjsVVnLkxF6d4PjilIs
            TMumZsMA06woxcICWxgD1hcGsRmlC75jkPnvi/HA7UehGu4eUmM8Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T09:24:44Z"
    mac: ENC[AES256_GCM,data:GEBEVxsUiyux0ABDo+HjyIClbiOL3hu/UXw2kogADJ+hfFezFTtrIh9vjTqVszN1fXqOBka5a8fJg6Kcef5F/J8+I6Gm90cttuCJpY6kLM1h0kYivp4frNIXJE5gajLgmLyx48l11jiG+nfBJtreduraybQOECGpKVp2LWhi8OI=,iv:1D8ee/xl34FU90iSZVCLlzgmzqSyxj9dGsJuFscQ7kY=,tag:UIPQTpLLqdUuPfDE+6wQ7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
