apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: potber-api
  namespace: potber-prod
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: potber-api
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: potber-auth
  namespace: potber-prod
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: potber-auth
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: potber-client
  namespace: potber-prod
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: potber-client
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: imgpot
  namespace: potber-prod
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: imgpot
  updatePolicy:
    updateMode: "Off"
