apiVersion: v1
kind: Secret
metadata:
    name: ghcr-creds
    namespace: potber-prod
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:t1lC5VTLjIpvrBArZi1jcPKO+VePeOAIHptPnqLqbWHoIg/xJaJMozW1cYzCmHXXJy8OTa7a6+VhtmuCfiP/A5WSSBqVdDTL05FnKWNNpKwubv1PPITS0BhNkHUxzhalQPlV+QoeH1NvAWjKnSgLqmET7IaBgyUqXTrW77cRB8Zze0zkbaUqXA99jWdgt3l3M5nCbvrUIX/VuTlv1Ol+8eQh9g4K7Xo99q1Nifnkl0KCWtrlnH8f1NDTTnxKIbAh/ry3CLCcVKR4cQyfP06J5pa43Z6z17z3th2URfkCdd7+6kf1FkWSNUuTvwaOdCSCqZsV5YtO8sChDByYWdxi12/7sTK2BZ2sUXiTJa+MxyuiHVFy4Gipmw==,iv:QRM51ByY4wOrX92PPLTUXrMHLk8EcYa4fCT/1KzkgYE=,tag:4WUVez/2Em6lF5TqJWWUpA==,type:str]
sops:
    age:
        - recipient: age1v64geenru82d3f2fl534lsu8dwdqlvnx665gsx4yxq4e3cdkyyzq38kgd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleFFjTm5XTlBqSlBJVFRv
            NlNYSGZCSDZFU0xDdmY2WUxwbmNtRzBoQmdRCm1OaEVPTnIyYVRLU0M1VmNuc3Y0
            QkRnaDI2cHBYL1BKT2x3L2cyelNoYVkKLS0tIEdjd0JjZnRXNWovZU5UUlFuRVJN
            ZlYyVFJZb2t1S2szb01YODBJODIyMUEKR9kQvsBAsXxhTUbMPtSMgGJLHM0ef5t3
            3ksuJCGYjvOCj9Q4jm7UFLu4t3b7oew1H643Ez6yaw7gHjptRzVm0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T14:56:16Z"
    mac: ENC[AES256_GCM,data:SqqikqHSBV9oljP1jEb6gpbmjTSGqMij0wt2hSq2qUIOAzbINPD1QA+0LOAF0iinLN4fMimcfVnZsSMsVoEMLhpz0iP98kZc32sw33Ln1HFs7jOsyYNL5heHB8eWhRmrDKy5MH6wVXxWoKChxlkswITusBMBT/UCUefY+a3AYwM=,iv:lhydczLxIs5pntnmNEls77ND3geiqbIE2TZtOVPeCPs=,tag:ynNSY2lZuij1ftDqwyM6Hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
