apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: potber-prod
resources:
  - ../../base
configMapGenerator:
  - name: imgpot-config
    envs:
      - imgpot.env
secretGenerator:
  - name: imgpot-secret
    envs:
      - imgpot.secret.env
images:
  - name: ghcr.io/potber/imgpot
    newTag: 1.0.0
replicas:
  - name: imgpot
    count: 1
patches:
  - path: patch-imgpot-ingress.yaml
