apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pr-107.yaml
  - pr-124.yaml
  - pr-125.yaml
  - pr-126.yaml
  - pr-127.yaml
  - pr-128.yaml
  - pr-129.yaml
  - pr-130.yaml
