apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - potber-api.yaml
  - potber-api-test.yaml
  - potber-auth.yaml
  - potber-auth-test.yaml
  - imgpot.yaml
  - potber-client.yaml
  - potber-client-test.yaml
